# This is your CI/CD pipeline - runs automatically on every push
name: Azure Alert System -Deployment Validation

on:
 push:
  branches:
   - main:
jobs:
  validate:
   runs-on: ubuntu-latest
   steps:
     -name: Checkout repository
      uses: actions/checkout@v3

      -name: Check required files exist
       run: |
        echo "Running Deployment Validation..."
        echo " Checking README exists ..."
        ls README.md && echo "README Found" || echo "README missing"
        echo "Check Screenshot Found..."
        ls screenshot/&& echo "Screenshots found" || echo "No Screenshots"
        echo "Validation Complete."

       -name: Print System Info
        run: |
          echo "Pipeline run by: ${{ github.actor }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
          echo "Deployment validation passed successfully."
        
  
         
     
     
     
     

     
     
   
